float pabs(float x);
int   pround(float x);
int   pfloor(float x);
int   pceil(float x);
float pfact(int x);
float ppow(float x,int exp);
float psquare(float x);
float pcos(float x);
float psin(float x);
float patan(float x);
float patan2(float y, float x);
float patan3(float y, float x);
float pexp(float x);
float psqrt(float n);
float plog(float x);
float pmean(unsigned short *data,long num);
float pfmean(float *data,long num);
double pdet2(double a00,double a01,double a10,double a11);
double pdet3(double m[][3]);
void pinvert3(double minv[][3],double m[][3],double det);
